def cpRed(message):
  print("\033[91m{}\033[00m" .format(message))
def cpGreen(message):
  print("\033[92m{}\033[00m" .format(message))
def cpYellow(message):
  print("\033[93m{}\033[00m" .format(message))
def cpPurple(message):
  print("\033[95m{}\033[00m" .format(message))
def cpCyan(message):
  print("\033[96m{}\033[00m" .format(message))

cpGreen("Hello!")
print("I am parker02311 a Roblox developer who makes tons of code, here on my github you can find all of my open source projects for you to download and setup for 100% free!")
print()
cpCyan("Programming Launguages")
print(" LUA")
print(" Python")
print(" HTML (More to learn)")
print(" CSS (More to learn)")
print(" Javascript/Node (More to learn)")
print(" C++ (Plan to learn)")
print()
cpYellow("Projects")
print(" Pembroke Pines Admin System")
print(" State of Rubicon")
print(" Redon Tech Products Loader")
print()
cpRed("Planned Projects")
print(" Pembroke Pines Chassis Rework")
print(" Redon Tech Fire System V2.0 (Open Source)")
print(" Redon Tech Product Puchasing Hub")
print(" And Many More!")
print()
cpPurple("Other")
print("Questions, comments, or concerns you can find me at:")
print(" Discord: parker02311#3460 (Recomended)")
print(" YouTube: parker02311")
print(" Email: parker02311contact@gmail.com")
print()
print("Need any help coding? Sorry, but I am not a teacher and would not be a very great one I recomend you check out whatever documentation you can find. Here are some resources that I use:")
print(" Roblox Documentation")
print(" Python Documentation")
print(" Discord.py Documentation")
print(" Quart Documentation")
print(" Flask Documentation")
print(" Stack Overflow")
